### ISSUE TITLE
Heroku deployment does not work as specified

### ISSUE THREAD

**Issue by thestumonkey** [Betterment/test_track#38]
I clicked the deploy to heroku button and when I start the dynos, this is in the logs:
```
2017-03-30T10:05:04.141611+00:00 heroku[web.1]: Process exited with status 1
2017-03-30T10:05:59.921567+00:00 heroku[web.1]: State changed from crashed to starting
2017-03-30T10:06:04.032458+00:00 heroku[web.1]: Starting process with command `bundle exec puma -C config/puma.rb`
2017-03-30T10:06:06.829457+00:00 heroku[web.1]: Process exited with status 1
2017-03-30T10:06:06.839395+00:00 heroku[web.1]: State changed from starting to crashed
2017-03-30T10:06:06.550449+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2017-03-30T10:06:06.550462+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2017-03-30T10:06:06.553025+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2017-03-30T10:06:06.553026+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2017-03-30T10:06:06.683988+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.2.0/bin/puma)
2017-03-30T10:06:06.684016+00:00 app[web.1]: KeyError: key not found: "PUMA_THREAD_COUNT"
2017-03-30T10:06:06.684017+00:00 app[web.1]:   config/puma.rb:11:in `fetch'
2017-03-30T10:06:06.684018+00:00 app[web.1]:   config/puma.rb:11:in `_load_from'
```

**Comment by jmileham** [comment]
Thanks for reporting. We'll get it patched up ASAP. I wonder if there's any way that we could regression protect this feature with an automated test... obviously we don't stand up a fresh heroku instance every day.

**Comment by thestumonkey** [comment]
That is literally the fastest I've ever seen one of my reported issues resolved.  Do I need to delete my heroku app and press the button again?

**Comment by jmileham** [comment]
That would be an easy way to go if you're not invested in that instance, or you can push up a fresh copy of `master` to your running app via git and it should Just Work™.  Let me know if you have any trouble. Marking as closed for now!
